'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, CalendarDays, CheckCircle2, Clock3, ExternalLink, FileText, History, MessageCircle, RefreshCw, ShieldCheck, Stethoscope, WalletCards } from 'lucide-react';
import { Button } from '@/components/ui/button';

const patient = { name: 'Sok Dara', code: 'PT000100', username: '@dara_sok', phone: '012 345 678', updated: 'Today, 10:24 AM' };
const appointments = [
  { procedure: 'Dental Cleaning', date: 'August 15, 2026', time: '10:30 AM', dentist: 'Dr. Chan Dara', status: 'Confirmed', location: 'Preah Chan Dental Clinic' },
  { procedure: 'Root Canal Review', date: 'August 15, 2026', time: '11:30 AM', dentist: 'Dr. Chan Dara', status: 'Booked', location: 'Preah Chan Dental Clinic' },
];
const history = [
  { date: 'July 27, 2026', procedure: 'Root Canal Preparation', tooth: 'Tooth #36', dentist: 'Dr. Chan Dara' },
  { date: 'July 15, 2026', procedure: 'Dental Examination & X-ray', tooth: 'Tooth #36', dentist: 'Dr. Chan Dara' },
  { date: 'January 10, 2026', procedure: 'Scaling & Cleaning', tooth: 'Full Mouth', dentist: 'Dr. Dara Sok' },
];
const recalls = [
  { name: 'Root Canal Review', due: 'August 15, 2026', status: 'Upcoming' },
  { name: 'Routine Cleaning', due: 'January 27, 2027', status: 'Scheduled' },
];

function Badge({ children, tone = 'green' }: { children: React.ReactNode; tone?: 'green' | 'amber' | 'blue' }) { const tones = { green: 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-300', amber: 'border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-300', blue: 'border-blue-200 bg-blue-50 text-blue-700 dark:border-blue-500/30 dark:bg-blue-500/10 dark:text-blue-300' }; return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-bold ${tones[tone]}`}>{children}</span>; }
function Card({ title, subtitle, icon, children, className = '' }: { title: string; subtitle?: string; icon: React.ReactNode; children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-border bg-card/95 p-5 shadow-sm ${className}`}><div className="mb-4 flex items-start gap-3 border-b border-border/60 pb-4"><div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary">{icon}</div><div><h2 className="text-lg font-bold">{title}</h2>{subtitle && <p className="text-sm text-muted-foreground">{subtitle}</p>}</div></div>{children}</section>; }
function Field({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-border bg-muted/30 px-3.5 py-3 dark:bg-background/20"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }

export function TelegramPatientPortalWorkspace() {
  const router = useRouter();
  const [feedback, setFeedback] = useState('');
  const [refreshed, setRefreshed] = useState('Today, 10:24 AM');
  const refresh = () => { setRefreshed('Just now'); setFeedback('Portal preview refreshed.'); };
  return <div className="mx-auto max-w-[1250px] space-y-5 pb-10"><div className="flex flex-wrap items-start justify-between gap-4"><div><Button variant="ghost" className="-ml-2 text-muted-foreground" onClick={() => router.push('/visit-completion')}><ArrowLeft className="size-4"/>Back</Button><p className="mt-3 text-xs font-bold uppercase tracking-[0.28em] text-primary/80">Telegram Patient Portal</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Patient Portal Preview</h1><p className="mt-1 text-sm text-muted-foreground">A staff-side preview of information available after Telegram linking</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => router.push('/telegram-linking')}><MessageCircle className="size-4"/>View Linked Account</Button><Button onClick={refresh}><RefreshCw className="size-4"/>Refresh Portal</Button></div></div>{feedback && <div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-800 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-200"><CheckCircle2 className="size-5"/>{feedback}</div>}
    <section className="rounded-2xl border border-emerald-200 bg-emerald-50/60 p-5 shadow-sm dark:border-emerald-500/30 dark:bg-emerald-500/10"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-bold">{patient.name}</h2><Badge>Linked · Active</Badge></div><p className="mt-1 text-sm text-muted-foreground">{patient.code} · Telegram {patient.username}</p></div><div className="text-right text-sm"><p className="text-xs text-muted-foreground">Last Portal Update</p><p className="font-semibold">{refreshed}</p></div></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Field label="Patient Code" value={patient.code}/><Field label="Telegram" value={patient.username}/><Field label="Phone" value={patient.phone}/></div></section>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Next Appointment</p><p className="mt-2 text-lg font-black">Aug 15, 2026</p><p className="text-xs text-muted-foreground">10:30 AM · Confirmed</p></div><div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Treatment Progress</p><p className="mt-2 text-lg font-black">2 of 3 stages</p><p className="text-xs text-muted-foreground">Root Canal · In Progress</p></div><div className="rounded-2xl border border-amber-200 bg-amber-50/60 p-5 shadow-sm dark:border-amber-500/30 dark:bg-amber-500/10"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Outstanding Balance</p><p className="mt-2 text-lg font-black">$85.00</p><p className="text-xs text-muted-foreground">Partially Paid</p></div><div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Next Recall</p><p className="mt-2 text-lg font-black">Aug 15, 2026</p><p className="text-xs text-muted-foreground">Root Canal Review</p></div></div>
    <div className="grid gap-5 xl:grid-cols-[1.35fr_0.65fr]"><div className="space-y-5"><Card title="Upcoming Appointments" subtitle="Read-only appointment information" icon={<CalendarDays className="size-5"/>}><div className="space-y-3">{appointments.map((appointment) => <div key={`${appointment.procedure}-${appointment.time}`} className="rounded-xl border border-border bg-muted/20 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-bold">{appointment.procedure}</p><p className="mt-1 text-sm text-muted-foreground">{appointment.date} · {appointment.time}</p></div><Badge tone={appointment.status === 'Confirmed' ? 'green' : 'blue'}>{appointment.status}</Badge></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2"><span><b>Dentist:</b> {appointment.dentist}</span><span><b>Location:</b> {appointment.location}</span></div></div>)}</div></Card>
    <Card title="Treatment Progress" subtitle="Root Canal Treatment — Tooth #36" icon={<Stethoscope className="size-5"/>}><div className="flex items-center justify-between text-sm"><span className="font-semibold">2 of 3 stages completed</span><Badge tone="blue">In Progress</Badge></div><div className="mt-3 h-3 overflow-hidden rounded-full bg-muted"><div className="h-full w-2/3 rounded-full bg-primary"/></div><div className="mt-4 grid gap-2 sm:grid-cols-3"><div className="rounded-xl border border-emerald-200 bg-emerald-50/60 p-3 text-sm dark:border-emerald-500/30 dark:bg-emerald-500/10"><CheckCircle2 className="size-4 text-emerald-600"/><p className="mt-1 font-semibold">Examination & X-ray</p><p className="text-xs text-muted-foreground">Completed</p></div><div className="rounded-xl border border-emerald-200 bg-emerald-50/60 p-3 text-sm dark:border-emerald-500/30 dark:bg-emerald-500/10"><CheckCircle2 className="size-4 text-emerald-600"/><p className="mt-1 font-semibold">Root Canal Preparation</p><p className="text-xs text-muted-foreground">Completed</p></div><div className="rounded-xl border border-amber-200 bg-amber-50/60 p-3 text-sm dark:border-amber-500/30 dark:bg-amber-500/10"><Clock3 className="size-4 text-amber-600"/><p className="mt-1 font-semibold">Permanent Restoration</p><p className="text-xs text-muted-foreground">Next step</p></div></div></Card>
    <Card title="Treatment History" subtitle="Completed visits and procedures" icon={<History className="size-5"/>}><div className="space-y-3">{history.map((item) => <div key={`${item.date}-${item.procedure}`} className="flex flex-wrap items-start justify-between gap-3 border-b border-border/60 pb-3 last:border-0 last:pb-0"><div><p className="font-semibold">{item.procedure}</p><p className="text-sm text-muted-foreground">{item.date} · {item.tooth}</p><p className="text-xs text-muted-foreground">{item.dentist}</p></div><Badge>Completed</Badge></div>)}</div></Card></div>
    <div className="space-y-5"><Card title="Financial Summary" subtitle="Latest invoice information" icon={<WalletCards className="size-5"/>}><div className="rounded-xl border border-amber-200 bg-amber-50/60 p-4 dark:border-amber-500/30 dark:bg-amber-500/10"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">Outstanding Balance</p><p className="mt-1 text-3xl font-black">$85.00</p><Badge tone="amber">Partially Paid</Badge></div><div className="mt-4 grid gap-2"><Field label="Latest Invoice" value="INV-2026-0108"/><Field label="Invoice Total" value="$185.00"/><Field label="Paid" value="$100.00"/><Field label="Remaining" value="$85.00"/></div><Button variant="outline" className="mt-4 w-full" onClick={() => router.push('/invoice')}><FileText className="size-4"/>View Invoice</Button></Card>
    <Card title="Recall Reminders" subtitle="Upcoming care reminders" icon={<Clock3 className="size-5"/>}><div className="space-y-3">{recalls.map((recall) => <div key={recall.name} className="rounded-xl border border-border bg-muted/20 p-3"><div className="flex items-start justify-between gap-2"><p className="text-sm font-bold">{recall.name}</p><Badge tone={recall.status === 'Scheduled' ? 'green' : 'blue'}>{recall.status}</Badge></div><p className="mt-2 text-xs text-muted-foreground">Due: <span className="font-semibold text-foreground">{recall.due}</span></p><p className="mt-1 text-xs text-muted-foreground">Reminder method: Telegram</p></div>)}</div></Card><Card title="Telegram Link Information" subtitle="Mock account status" icon={<ShieldCheck className="size-5"/>}><div className="space-y-3"><Field label="Username" value={patient.username}/><Field label="Status" value="Active"/><Field label="Last Update" value={patient.updated}/></div></Card></div></div>
  </div>;
}