'use client';

import { AlertTriangle, ArrowLeft, Bell, CalendarDays, CheckCircle2, Clock3, Mail, MessageSquare, Phone, Search, Send, User, X, XCircle } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';

type Bucket = 'Due Today' | 'Overdue' | 'Upcoming';
type Reminder = 'Pending' | 'Sent' | 'Failed' | 'Booked' | 'No Response';
type Recall = { id: string; name: string; code: string; phone: string; type: string; dueDate: string; dueLabel: string; lastVisit: string; bucket: Bucket; reminder: Reminder; method: string; lastReminder: string; notes: string; daysOverdue: number };

const initialRecalls: Recall[] = [
  { id: 'recall-1', name: 'Sok Dara', code: 'PT000128', phone: '012 345 678', type: '6-Month Cleaning', dueDate: 'July 27, 2026', dueLabel: 'Today', lastVisit: 'Jan 27, 2026', bucket: 'Due Today', reminder: 'Sent', method: 'Telegram', lastReminder: 'Today, 8:10 AM', notes: 'Routine preventive cleaning recommended.', daysOverdue: 0 },
  { id: 'recall-2', name: 'Maly Chenda', code: 'PT000214', phone: '010 228 441', type: 'Regular Check-up', dueDate: 'July 27, 2026', dueLabel: 'Today', lastVisit: 'Jan 27, 2026', bucket: 'Due Today', reminder: 'Pending', method: 'Phone', lastReminder: 'Not sent', notes: 'Patient prefers morning appointments.', daysOverdue: 0 },
  { id: 'recall-3', name: 'Chan Sreyneang', code: 'PT000087', phone: '097 883 120', type: 'Routine Check-up', dueDate: 'July 18, 2026', dueLabel: '9 days overdue', lastVisit: 'Jan 18, 2026', bucket: 'Overdue', reminder: 'Failed', method: 'Phone', lastReminder: 'July 18, 2026', notes: 'Phone number busy on last attempt.', daysOverdue: 9 },
  { id: 'recall-4', name: 'Vannak Lim', code: 'PT000301', phone: '015 441 220', type: 'Root Canal Follow-up', dueDate: 'July 12, 2026', dueLabel: '15 days overdue', lastVisit: 'Apr 12, 2026', bucket: 'Overdue', reminder: 'No Response', method: 'Telegram', lastReminder: 'July 13, 2026', notes: 'Review post-treatment healing.', daysOverdue: 15 },
  { id: 'recall-5', name: 'Sophea Keo', code: 'PT000176', phone: '011 339 776', type: 'Crown Review', dueDate: 'July 30, 2026', dueLabel: 'Due in 3 days', lastVisit: 'Jan 30, 2026', bucket: 'Upcoming', reminder: 'Pending', method: 'SMS', lastReminder: 'Not sent', notes: 'Crown margin review.', daysOverdue: 0 },
  { id: 'recall-6', name: 'Rithy Sam', code: 'PT000263', phone: '012 990 412', type: 'Implant Review', dueDate: 'August 5, 2026', dueLabel: 'Due next week', lastVisit: 'Feb 5, 2026', bucket: 'Upcoming', reminder: 'Booked', method: 'Email', lastReminder: 'July 20, 2026', notes: 'Appointment already requested.', daysOverdue: 0 },
];

const badge = (value: string) => value === 'Sent' || value === 'Booked' ? 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-300' : value === 'Failed' || value === 'No Response' || value === 'Overdue' ? 'border-rose-200 bg-rose-50 text-rose-700 dark:border-rose-500/30 dark:bg-rose-500/10 dark:text-rose-300' : value === 'Due Today' ? 'border-blue-200 bg-blue-50 text-blue-700 dark:border-blue-500/30 dark:bg-blue-500/10 dark:text-blue-300' : 'border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-300';
const methodIcon = (method: string) => method === 'Phone' ? <Phone className="size-3.5"/> : method === 'SMS' ? <MessageSquare className="size-3.5"/> : method === 'Email' ? <Mail className="size-3.5"/> : <Send className="size-3.5"/>;

function RecallDetail({ recall, onClose }: { recall: Recall; onClose: () => void }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={onClose}><div className="w-full max-w-lg rounded-2xl border border-border bg-card p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Recall Detail</p><h2 className="mt-1 text-xl font-bold">{recall.name}</h2><p className="text-sm text-muted-foreground">{recall.code}</p></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-muted-foreground hover:bg-muted"><X className="size-5"/></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[['Phone', recall.phone], ['Recall Type', recall.type], ['Due Date', recall.dueDate], ['Days Overdue', recall.daysOverdue ? `${recall.daysOverdue} days` : '—'], ['Preferred Method', recall.method], ['Last Reminder', recall.lastReminder], ['Reminder Status', recall.reminder]].map(([label, value]) => <div key={label} className="rounded-xl border border-border bg-background/40 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div><div className="mt-4 rounded-xl border border-border bg-muted/30 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Notes</p><p className="mt-1 text-sm">{recall.notes}</p></div><div className="mt-5 flex justify-end"><Button onClick={onClose}>Close</Button></div></div></div>;
}

function RecallTable({ title, records, onOpen, onSend, onRetry }: { title: string; records: Recall[]; onOpen: (recall: Recall) => void; onSend: (recall: Recall) => void; onRetry: (recall: Recall) => void }) {
  return <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="flex items-center justify-between border-b border-border p-5"><div><h2 className="flex items-center gap-2 text-lg font-bold"><CalendarDays className="size-5 text-primary"/>{title}</h2><p className="text-sm text-muted-foreground">{records.length} patient{records.length === 1 ? '' : 's'} need attention</p></div><span className={`rounded-full border px-2.5 py-1 text-xs font-bold ${badge(title)}`}>{title}</span></div>{records.length ? <div className="overflow-x-auto"><table className="min-w-[980px] w-full"><thead className="bg-muted/40"><tr>{['Patient','Recall Type','Due Date','Last Visit','Reminder','Contact','Actions'].map((heading) => <th key={heading} className="px-4 py-3 text-left text-xs font-bold uppercase tracking-wide text-muted-foreground">{heading}</th>)}</tr></thead><tbody>{records.map((recall) => <tr key={recall.id} className="border-t border-border hover:bg-primary/5"><td className="px-4 py-4"><p className="text-sm font-bold">{recall.name}</p><p className="text-xs text-muted-foreground">{recall.code} · {recall.phone}</p></td><td className="px-4 py-4 text-sm">{recall.type}</td><td className="px-4 py-4"><p className="text-sm">{recall.dueDate}</p><span className={`mt-1 inline-flex rounded-full border px-2 py-0.5 text-xs font-semibold ${recall.bucket === 'Overdue' ? badge('Overdue') : badge(recall.bucket)}`}>{recall.dueLabel}</span></td><td className="px-4 py-4 text-sm">{recall.lastVisit}</td><td className="px-4 py-4"><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${badge(recall.reminder)}`}>{recall.reminder}</span></td><td className="px-4 py-4"><span className="inline-flex items-center gap-1.5 text-sm">{methodIcon(recall.method)}{recall.method}</span></td><td className="px-4 py-4"><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => onOpen(recall)}>Open Patient</Button>{recall.reminder === 'Failed' ? <Button variant="outline" size="sm" onClick={() => onRetry(recall)}>Retry</Button> : recall.reminder !== 'Sent' && recall.reminder !== 'Booked' ? <Button size="sm" onClick={() => onSend(recall)}><Bell className="size-3.5"/>Send Reminder</Button> : null}</div></td></tr>)}</tbody></table></div> : <div className="p-10 text-center text-sm text-muted-foreground">No recall patients found</div>}</section>;
}

export function RecallDashboardWorkspace() {
  const router = useRouter();
  const [recalls, setRecalls] = useState(initialRecalls);
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState<Bucket | 'All'>('All');
  const [typeFilter, setTypeFilter] = useState('All');
  const [reminderFilter, setReminderFilter] = useState<Reminder | 'All'>('All');
  const [selected, setSelected] = useState<Recall | null>(null);
  const [feedback, setFeedback] = useState('');
  const filtered = useMemo(() => recalls.filter((recall) => (!search || [recall.name, recall.code, recall.phone].some((value) => value.toLowerCase().includes(search.toLowerCase()))) && (statusFilter === 'All' || recall.bucket === statusFilter) && (typeFilter === 'All' || recall.type === typeFilter) && (reminderFilter === 'All' || recall.reminder === reminderFilter)), [recalls, reminderFilter, search, statusFilter, typeFilter]);
  const byBucket = (bucket: Bucket) => filtered.filter((recall) => recall.bucket === bucket);
  const updateReminder = (recall: Recall) => { setRecalls((current) => current.map((item) => item.id === recall.id ? { ...item, reminder: 'Sent', lastReminder: 'Today, 10:42 AM' } : item)); setFeedback(`Reminder marked as sent for ${recall.name}.`); setSelected(null); };
  const retry = (recall: Recall) => { updateReminder(recall); };

  return <div className="mx-auto max-w-[1250px] space-y-5 pb-10"><div className="flex flex-wrap items-start justify-between gap-4"><div><Button variant="ghost" className="-ml-2 text-muted-foreground" onClick={() => router.push('/')}><ArrowLeft className="size-4"/>Back to Dashboard</Button><p className="mt-3 text-xs font-bold uppercase tracking-[0.28em] text-primary/80">Follow-up & Recall</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Recall Dashboard</h1><p className="mt-1 text-sm text-muted-foreground">Monitor upcoming and overdue patient recalls</p></div><div className="rounded-xl border border-border bg-card px-4 py-3 text-right"><p className="text-xs text-muted-foreground">Current mock date</p><p className="font-bold">July 27, 2026</p></div></div>{feedback && <div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-800 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-200"><CheckCircle2 className="size-5"/>{feedback}</div>}
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Due Today', '8 Patients', CalendarDays], ['Overdue', '14 Patients', AlertTriangle], ['Upcoming', '27 Patients', Clock3], ['Reminder Success Rate', '86%', CheckCircle2]].map(([label, value, Icon]) => <div key={String(label)} className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wide text-muted-foreground">{label}</p><Icon className="size-5 text-primary"/></div><p className="mt-2 text-2xl font-black">{value}</p>{label === 'Reminder Success Rate' && <><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full w-[86%] rounded-full bg-emerald-500"/></div><p className="mt-2 text-xs text-muted-foreground">37 successful · 6 failed · 43 sent</p></>}</div>)}</div>
    <section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-end"><label className="flex-1 text-xs font-semibold text-muted-foreground">Search patients<div className="relative mt-1.5"><Search className="absolute left-3 top-3 size-4"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Name, patient code, or phone..." className="h-10 w-full rounded-xl border border-border bg-background pl-9 pr-3 text-sm"/></div></label><label className="text-xs font-semibold text-muted-foreground">Recall Status<select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as Bucket | 'All')} className="mt-1.5 h-10 rounded-xl border border-border bg-background px-3 text-sm"><option>All</option><option>Due Today</option><option>Overdue</option><option>Upcoming</option></select></label><label className="text-xs font-semibold text-muted-foreground">Recall Type<select value={typeFilter} onChange={(event) => setTypeFilter(event.target.value)} className="mt-1.5 h-10 rounded-xl border border-border bg-background px-3 text-sm"><option>All</option>{Array.from(new Set(recalls.map((recall) => recall.type))).map((type) => <option key={type}>{type}</option>)}</select></label><label className="text-xs font-semibold text-muted-foreground">Reminder Status<select value={reminderFilter} onChange={(event) => setReminderFilter(event.target.value as Reminder | 'All')} className="mt-1.5 h-10 rounded-xl border border-border bg-background px-3 text-sm"><option>All</option><option>Pending</option><option>Sent</option><option>Failed</option><option>No Response</option></select></label></div></section>
    <RecallTable title="Due Today" records={byBucket('Due Today')} onOpen={setSelected} onSend={updateReminder} onRetry={retry}/><RecallTable title="Overdue" records={byBucket('Overdue')} onOpen={setSelected} onSend={updateReminder} onRetry={retry}/><RecallTable title="Upcoming" records={byBucket('Upcoming')} onOpen={setSelected} onSend={updateReminder} onRetry={retry}/>{selected && <RecallDetail recall={selected} onClose={() => setSelected(null)}/>}</div>;
}