'use client';

import { AlertTriangle, ArrowLeft, CheckCircle2, DollarSign, FileText, Percent, RotateCcw, ShieldCheck, User, XCircle } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';

type DiscountType = 'Percentage' | 'Fixed Amount';
type ApprovalStatus = 'Pending Approval' | 'Approved' | 'Rejected';

const INVOICE = {
  number: 'INV-2026-00428', patient: 'Sok Dara', code: 'PT000128', appointment: 'July 27, 2026',
  items: [['Scaling & Polishing', 35], ['Composite Filling #16', 45], ['Composite Filling #26', 45]] as const,
};
const SUBTOTAL = INVOICE.items.reduce((total, [, amount]) => total + amount, 0);

function money(value: number) { return `$${value.toFixed(2)}`; }
function statusClass(status: ApprovalStatus) {
  return status === 'Approved' ? 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-300' : status === 'Rejected' ? 'border-rose-200 bg-rose-50 text-rose-700 dark:border-rose-500/30 dark:bg-rose-500/10 dark:text-rose-300' : 'border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-300';
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-border bg-background/40 px-3 py-2.5"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold text-foreground">{value}</p></div>; }

export function DiscountApprovalWorkspace() {
  const router = useRouter();
  const [type, setType] = useState<DiscountType>('Percentage');
  const [value, setValue] = useState('10');
  const [reason, setReason] = useState('Returning patient courtesy discount.');
  const [status, setStatus] = useState<ApprovalStatus>('Pending Approval');
  const [rejectionReason, setRejectionReason] = useState('');
  const [showRejectReason, setShowRejectReason] = useState(false);

  const numericValue = Math.max(0, Number(value) || 0);
  const discountAmount = useMemo(() => Math.min(SUBTOTAL, type === 'Percentage' ? SUBTOTAL * Math.min(100, numericValue) / 100 : numericValue), [numericValue, type]);
  const newTotal = SUBTOTAL - discountAmount;
  const invalid = type === 'Percentage' ? numericValue > 100 : numericValue > SUBTOTAL;
  const approvalRequired = discountAmount > 10;

  const reset = () => { setType('Percentage'); setValue('10'); setReason('Returning patient courtesy discount.'); setStatus('Pending Approval'); setRejectionReason(''); setShowRejectReason(false); };
  const reject = () => { if (showRejectReason && rejectionReason.trim()) setStatus('Rejected'); else setShowRejectReason(true); };

  return <div className="mx-auto max-w-[1200px] space-y-5 pb-10">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><Button variant="ghost" className="-ml-2 text-muted-foreground" onClick={() => router.push('/invoice')}><ArrowLeft className="size-4" />Back to Invoice</Button><p className="mt-3 text-xs font-bold uppercase tracking-[0.28em] text-primary/80">Billing & Payment</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-foreground">Discount Approval</h1><p className="mt-1 text-sm text-muted-foreground">Review and authorize an invoice discount request</p></div><span className={`inline-flex items-center gap-2 rounded-full border px-3 py-1.5 text-sm font-bold ${statusClass(status)}`}>{status === 'Approved' ? <CheckCircle2 className="size-4"/> : status === 'Rejected' ? <XCircle className="size-4"/> : <AlertTriangle className="size-4"/>}{status}</span></div>
    <section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Info label="Invoice" value={INVOICE.number}/><Info label="Patient" value={INVOICE.patient}/><Info label="Patient Code" value={INVOICE.code}/><Info label="Appointment" value={INVOICE.appointment}/><Info label="Requested By" value="Srey Mom · Receptionist"/></div></section>
    <div className="grid gap-5 lg:grid-cols-[1.3fr_0.7fr]"><div className="space-y-5"><section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-bold"><FileText className="size-5 text-primary"/>Invoice Summary</h2><div className="mt-4 space-y-2">{INVOICE.items.map(([item, amount]) => <div key={item} className="flex justify-between rounded-xl bg-muted/30 px-3 py-2.5 text-sm"><span className="text-foreground">{item}</span><span className="font-semibold">{money(amount)}</span></div>)}<div className="mt-3 border-t border-border pt-3"><div className="flex justify-between text-sm"><span className="text-muted-foreground">Subtotal</span><span className="font-bold">{money(SUBTOTAL)}</span></div><div className="mt-2 flex justify-between text-sm"><span className="text-muted-foreground">Current Discount</span><span className="font-semibold text-rose-600">$0.00</span></div><div className="mt-2 flex justify-between text-sm"><span className="text-muted-foreground">Tax</span><span>$0.00</span></div><div className="mt-3 flex justify-between rounded-xl border border-primary/20 bg-primary/5 px-3 py-3"><span className="font-bold">Current Total</span><span className="text-lg font-black">{money(SUBTOTAL)}</span></div></div></div></section>
    <section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-bold"><Percent className="size-5 text-primary"/>Discount Request</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Discount Type<select value={type} onChange={(event) => setType(event.target.value as DiscountType)} className="mt-1.5 h-11 w-full rounded-xl border border-border bg-background px-3 text-sm font-normal"><option>Percentage</option><option>Fixed Amount</option></select></label><label className="text-sm font-semibold">Discount Value<div className="relative mt-1.5"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground">{type === 'Percentage' ? '%' : '$'}</span><input type="number" min="0" max={type === 'Percentage' ? 100 : SUBTOTAL} value={value} onChange={(event) => setValue(event.target.value)} className="h-11 w-full rounded-xl border border-border bg-background pl-8 pr-3 text-sm font-normal"/></div></label><label className="text-sm font-semibold sm:col-span-2">Reason<textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3} className="mt-1.5 w-full resize-none rounded-xl border border-border bg-background px-3 py-2 text-sm font-normal"/></label></div>{invalid && <p className="mt-3 flex items-center gap-2 text-sm font-semibold text-rose-600"><AlertTriangle className="size-4"/>{type === 'Percentage' ? 'Percentage cannot exceed 100%.' : `Fixed discount cannot exceed ${money(SUBTOTAL)}.`}</p>}</section>
    <section className="rounded-2xl border border-primary/20 bg-primary/5 p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-bold"><DollarSign className="size-5 text-primary"/>Discount Calculation Preview</h2><div className="mt-4 grid gap-3 sm:grid-cols-3"><Info label="Subtotal" value={money(SUBTOTAL)}/><Info label="Requested Discount" value={type === 'Percentage' ? `${numericValue}%` : money(numericValue)}/><Info label="Discount Amount" value={`-${money(discountAmount)}`}/></div><div className="mt-4 flex items-center justify-between rounded-xl border border-primary/20 bg-card px-4 py-3"><span className="font-bold">New Total</span><span className="text-2xl font-black text-primary">{money(newTotal)}</span></div></section></div>
    <aside className="space-y-5"><section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-bold"><ShieldCheck className="size-5 text-primary"/>Approval Requirement</h2><div className={`mt-4 rounded-xl border p-4 ${approvalRequired ? 'border-amber-200 bg-amber-50 text-amber-800 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-200' : 'border-emerald-200 bg-emerald-50 text-emerald-800 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-200'}`}><p className="font-bold">{approvalRequired ? 'Approval Required' : 'No Approval Required'}</p><p className="mt-1 text-sm">{approvalRequired ? 'This discount exceeds the receptionist mock authorization limit and requires administrator approval.' : 'This small discount can be applied within the mock authorization limit.'}</p></div></section><section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 className="flex items-center gap-2 text-lg font-bold"><User className="size-5 text-primary"/>Request Information</h2><div className="mt-4 space-y-3"><Info label="Requested By" value="Srey Mom"/><Info label="Role" value="Receptionist"/><Info label="Requested" value="July 27, 2026 at 10:42 AM"/><Info label="Approver" value={status === 'Approved' ? 'Administrator' : 'Administrator (mock)'}/>{status === 'Rejected' && <Info label="Rejection Reason" value={rejectionReason}/>}</div></section></aside></div>
    {showRejectReason && status === 'Pending Approval' && <section className="rounded-2xl border border-rose-200 bg-rose-50/60 p-5 dark:border-rose-500/30 dark:bg-rose-500/10"><label className="block text-sm font-semibold text-rose-900 dark:text-rose-100">Rejection Reason<textarea value={rejectionReason} onChange={(event) => setRejectionReason(event.target.value)} rows={2} placeholder="Optional rejection reason..." className="mt-1.5 w-full rounded-xl border border-rose-200 bg-background px-3 py-2 text-sm text-foreground"/></label></section>}
    <div className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-border bg-card p-4 shadow-sm"><Button variant="outline" onClick={() => router.push('/invoice')}>Cancel</Button><div className="flex flex-wrap gap-2">{status !== 'Pending Approval' && <Button variant="outline" onClick={reset}><RotateCcw className="size-4"/>Reset Mock</Button>}{status === 'Pending Approval' && <><Button variant="destructive" onClick={reject}><XCircle className="size-4"/>{showRejectReason ? 'Confirm Reject' : 'Reject'}</Button><Button disabled={invalid || !reason.trim()} onClick={() => setStatus('Approved')}><CheckCircle2 className="size-4"/>Approve Discount</Button></>}</div></div>
  </div>;
}