'use client';

import { ArrowLeft, ArrowUpRight, CalendarDays, CheckCircle2, FileText, History, Search, X, XCircle } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';

type TransactionType = 'Payment' | 'Refund' | 'Adjustment';
type Status = 'Completed' | 'Pending' | 'Failed' | 'Refunded';
type Transaction = {
  date: string; id: string; invoice: string; type: TransactionType; method: string; amount: number;
  status: Status; staff: string; patient: string; reference: string; dateTime: string; notes: string;
  originalPayment?: string; reason?: string; approvedBy?: string;
};

const transactions: Transaction[] = [
  { date: 'Jul 27, 2026', id: 'TXN-00428', invoice: 'INV-2026-00428', type: 'Payment', method: 'Cash', amount: 100, status: 'Completed', staff: 'Srey Mom', patient: 'Sok Dara', reference: 'CASH-072726-001', dateTime: 'July 27, 2026 at 10:42 AM', notes: 'Partial payment received at front desk.' },
  { date: 'Jul 18, 2026', id: 'TXN-00411', invoice: 'INV-2026-00411', type: 'Payment', method: 'KHQR', amount: 75, status: 'Completed', staff: 'Srey Mom', patient: 'Sok Dara', reference: 'KHQR-071826-014', dateTime: 'July 18, 2026 at 2:15 PM', notes: 'Payment received through KHQR.' },
  { date: 'Jun 10, 2026', id: 'TXN-00382', invoice: 'INV-2026-00382', type: 'Refund', method: 'Cash', amount: -25, status: 'Refunded', staff: 'Admin', patient: 'Sok Dara', reference: 'REF-061026-002', dateTime: 'June 10, 2026 at 11:05 AM', notes: 'Refund issued after duplicate payment.', originalPayment: 'TXN-00380', reason: 'Duplicate payment', approvedBy: 'Administrator' },
  { date: 'May 22, 2026', id: 'TXN-00341', invoice: 'INV-2026-00341', type: 'Adjustment', method: 'Manual Adjustment', amount: -10, status: 'Completed', staff: 'Admin', patient: 'Sok Dara', reference: 'ADJ-052226-001', dateTime: 'May 22, 2026 at 9:30 AM', notes: 'Billing correction applied.', reason: 'Billing correction', approvedBy: 'Administrator' },
  { date: 'Apr 14, 2026', id: 'TXN-00298', invoice: 'INV-2026-00298', type: 'Payment', method: 'Credit Card', amount: 360, status: 'Completed', staff: 'Srey Mom', patient: 'Sok Dara', reference: 'CARD-041426-008', dateTime: 'April 14, 2026 at 4:20 PM', notes: 'Full payment received.' },
];

const badge = (value: string) => value === 'Payment' || value === 'Completed' ? 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-300' : value === 'Refund' || value === 'Refunded' ? 'border-rose-200 bg-rose-50 text-rose-700 dark:border-rose-500/30 dark:bg-rose-500/10 dark:text-rose-300' : 'border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-300';
const money = (amount: number) => `${amount < 0 ? '-' : ''}$${Math.abs(amount).toFixed(2)}`;

function DetailModal({ transaction, onClose }: { transaction: Transaction; onClose: () => void }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={onClose}><div className="w-full max-w-lg rounded-2xl border border-border bg-card p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Transaction Detail</p><h2 className="mt-1 text-xl font-bold">{transaction.id}</h2></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-muted-foreground hover:bg-muted"><X className="size-5"/></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2">{[['Invoice', transaction.invoice], ['Patient', transaction.patient], ['Type', transaction.type], ['Date / Time', transaction.dateTime], ['Payment Method', transaction.method], ['Amount', money(transaction.amount)], ['Status', transaction.status], ['Reference', transaction.reference], ['Processed By', transaction.staff], ...(transaction.originalPayment ? [['Original Payment', transaction.originalPayment]] : []), ...(transaction.reason ? [['Reason', transaction.reason]] : []), ...(transaction.approvedBy ? [['Approved By', transaction.approvedBy]] : [])].map(([label, value]) => <div key={label} className="rounded-xl border border-border bg-background/40 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div><div className="mt-4 rounded-xl border border-border bg-muted/30 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Notes</p><p className="mt-1 text-sm">{transaction.notes}</p></div><div className="mt-5 flex justify-end"><Button onClick={onClose}>Close</Button></div></div></div>;
}

export function TransactionHistoryWorkspace() {
  const router = useRouter();
  const [search, setSearch] = useState('');
  const [type, setType] = useState<TransactionType | 'All'>('All');
  const [status, setStatus] = useState<Status | 'All'>('All');
  const [method, setMethod] = useState('All');
  const [selected, setSelected] = useState<Transaction | null>(null);
  const filtered = useMemo(() => { const query = search.toLowerCase().trim(); return transactions.filter((item) => (!query || [item.id, item.invoice, item.patient, item.reference].some((value) => value.toLowerCase().includes(query))) && (type === 'All' || item.type === type) && (status === 'All' || item.status === status) && (method === 'All' || item.method === method)); }, [method, search, status, type]);

  return <div className="mx-auto max-w-[1200px] space-y-5 pb-10"><div className="flex flex-wrap items-start justify-between gap-4"><div><Button variant="ghost" className="-ml-2 text-muted-foreground" onClick={() => router.push('/billing')}><ArrowLeft className="size-4"/>Back to Billing</Button><p className="mt-3 text-xs font-bold uppercase tracking-[0.28em] text-primary/80">Billing & Payment</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Transaction History</h1><p className="mt-1 text-sm text-muted-foreground">Review payments, refunds, and financial adjustments</p></div><div className="rounded-xl border border-border bg-card px-4 py-3 text-right"><p className="text-xs text-muted-foreground">Patient</p><p className="font-bold">Sok Dara</p><p className="text-xs text-muted-foreground">PT000128 · 012 345 678</p></div></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[['Total Billed', '$620.00'], ['Total Paid', '$535.00'], ['Refunded', '$25.00'], ['Adjustments', '-$10.00'], ['Outstanding', '$85.00']].map(([label, value]) => <div key={label} className="rounded-2xl border border-border bg-card p-4 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-black">{value}</p></div>)}</div>
    <section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-end"><label className="flex-1 text-xs font-semibold text-muted-foreground">Search transactions<div className="relative mt-1.5"><Search className="absolute left-3 top-3 size-4"/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Transaction ID, invoice, patient, reference..." className="h-10 w-full rounded-xl border border-border bg-background pl-9 pr-3 text-sm"/></div></label><label className="text-xs font-semibold text-muted-foreground">Type<select value={type} onChange={(event) => setType(event.target.value as TransactionType | 'All')} className="mt-1.5 h-10 rounded-xl border border-border bg-background px-3 text-sm"><option>All</option><option>Payment</option><option>Refund</option><option>Adjustment</option></select></label><label className="text-xs font-semibold text-muted-foreground">Status<select value={status} onChange={(event) => setStatus(event.target.value as Status | 'All')} className="mt-1.5 h-10 rounded-xl border border-border bg-background px-3 text-sm"><option>All</option><option>Completed</option><option>Pending</option><option>Failed</option><option>Refunded</option></select></label><label className="text-xs font-semibold text-muted-foreground">Method<select value={method} onChange={(event) => setMethod(event.target.value)} className="mt-1.5 h-10 rounded-xl border border-border bg-background px-3 text-sm"><option>All</option><option>Cash</option><option>KHQR</option><option>Credit Card</option><option>Manual Adjustment</option></select></label></div></section>
    <section className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><div className="border-b border-border p-5"><h2 className="flex items-center gap-2 text-lg font-bold"><History className="size-5 text-primary"/>Transaction Ledger</h2><p className="text-sm text-muted-foreground">Read-only mock financial history</p></div>{filtered.length ? <div className="overflow-x-auto"><table className="min-w-[950px] w-full"><thead className="bg-muted/40"><tr>{['Date','Transaction ID','Invoice','Type','Payment Method','Amount','Status','Staff','Action'].map((heading) => <th key={heading} className="px-4 py-3 text-left text-xs font-bold uppercase tracking-wide text-muted-foreground">{heading}</th>)}</tr></thead><tbody>{filtered.map((item) => <tr key={item.id} className="border-t border-border hover:bg-primary/5"><td className="px-4 py-4 text-sm">{item.date}</td><td className="px-4 py-4 text-sm font-bold">{item.id}</td><td className="px-4 py-4 text-sm">{item.invoice}</td><td className="px-4 py-4"><span className={`inline-flex items-center gap-1 rounded-full border px-2.5 py-1 text-xs font-semibold ${badge(item.type)}`}>{item.type === 'Payment' ? <ArrowUpRight className="size-3"/> : item.type === 'Refund' ? <XCircle className="size-3"/> : <FileText className="size-3"/>}{item.type}</span></td><td className="px-4 py-4 text-sm">{item.method}</td><td className={`px-4 py-4 text-sm font-bold ${item.amount < 0 ? 'text-rose-600' : 'text-emerald-700 dark:text-emerald-300'}`}>{money(item.amount)}</td><td className="px-4 py-4"><span className={`rounded-full border px-2.5 py-1 text-xs font-semibold ${badge(item.status)}`}>{item.status}</span></td><td className="px-4 py-4 text-sm">{item.staff}</td><td className="px-4 py-4"><Button variant="outline" size="sm" onClick={() => setSelected(item)}>View Detail</Button></td></tr>)}</tbody></table></div> : <div className="p-14 text-center"><XCircle className="mx-auto size-10 text-muted-foreground"/><h3 className="mt-3 font-bold">No transactions found</h3><p className="mt-1 text-sm text-muted-foreground">Try changing your search or filters.</p></div>}</section>{selected && <DetailModal transaction={selected} onClose={() => setSelected(null)}/>}</div>;
}