'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ArrowLeft, CheckCircle2, Copy, ExternalLink, Link2, MessageCircle, ShieldCheck, Smartphone, Unlink, User, X } from 'lucide-react';
import { Button } from '@/components/ui/button';

type LinkStatus = 'Not Linked' | 'Invite Ready' | 'Linked';
const PATIENT = { name: 'Sok Dara', code: 'PT000100', phone: '012 345 678', lastVisit: 'July 27, 2026' };
const MOCK_TOKEN = 'TG-7K9X-4P2M-8Q1A';

function StatusBadge({ status }: { status: LinkStatus }) {
  const styles = status === 'Linked' ? 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-300' : status === 'Invite Ready' ? 'border-amber-200 bg-amber-50 text-amber-700 dark:border-amber-500/30 dark:bg-amber-500/10 dark:text-amber-300' : 'border-slate-200 bg-slate-50 text-slate-700 dark:border-slate-700 dark:bg-slate-800 dark:text-slate-200';
  return <span className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-bold ${styles}`}><span className="size-2 rounded-full bg-current" />{status}</span>;
}
function Field({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-border bg-muted/30 px-3.5 py-3 dark:bg-background/20"><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold text-foreground">{value}</p></div>; }
function MockQr() { return <div className="relative grid size-48 grid-cols-9 gap-1 rounded-xl border-8 border-white bg-white p-3 shadow-lg" aria-label="Mock Telegram invitation QR visual"><div className="absolute left-3 top-3 size-9 border-4 border-slate-900"/><div className="absolute right-3 top-3 size-9 border-4 border-slate-900"/><div className="absolute bottom-3 left-3 size-9 border-4 border-slate-900"/><div className="col-span-9 grid grid-cols-9 gap-1 opacity-80">{Array.from({ length: 81 }, (_, index) => <span key={index} className={(index * 17 + 3) % 5 < 2 ? 'bg-slate-900' : 'bg-transparent'} />)}</div></div>; }

export function TelegramLinkingWorkspace() {
  const router = useRouter();
  const [status, setStatus] = useState<LinkStatus>('Not Linked');
  const [copied, setCopied] = useState(false);
  const [feedback, setFeedback] = useState('');
  const [unlinkOpen, setUnlinkOpen] = useState(false);
  const generateInvite = () => { setStatus('Invite Ready'); setFeedback('Mock invitation generated for this patient.'); setCopied(false); };
  const copyToken = () => { setCopied(true); setFeedback('Token copied.'); };
  const linkAccount = () => { if (status !== 'Invite Ready') { setFeedback('Generate an invitation before linking the Telegram account.'); return; } setStatus('Linked'); setFeedback('Telegram account linked successfully in this mock workspace.'); };
  const unlinkAccount = () => { setStatus('Not Linked'); setFeedback('Telegram account unlinked. Generate a new invitation to reconnect.'); setCopied(false); setUnlinkOpen(false); };

  return <div className="mx-auto max-w-[1100px] space-y-5 pb-10"><div className="flex flex-wrap items-start justify-between gap-4"><div><Button variant="ghost" className="-ml-2 text-muted-foreground" onClick={() => router.push('/visit-completion')}><ArrowLeft className="size-4"/>Back to Visit Completion</Button><p className="mt-3 text-xs font-bold uppercase tracking-[0.28em] text-primary/80">Follow-up, Recall & Telegram</p><h1 className="mt-1 text-3xl font-bold tracking-tight text-foreground">Telegram Linking</h1><p className="mt-1 text-sm text-muted-foreground">Connect an existing clinic patient record to a Telegram account</p></div><StatusBadge status={status}/></div>{feedback && <div className="flex items-center gap-2 rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm font-semibold text-primary"><CheckCircle2 className="size-5"/>{feedback}</div>}
    <section className="rounded-2xl border border-border bg-card/95 p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><User className="size-5 text-primary"/><div><h2 className="text-lg font-bold">Patient Context</h2><p className="text-sm text-muted-foreground">This patient record already exists in the clinic.</p></div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Patient" value={PATIENT.name}/><Field label="Patient Code" value={PATIENT.code}/><Field label="Phone" value={PATIENT.phone}/><Field label="Preferred Contact" value="Telegram"/></div></section>
    <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-border bg-card/95 p-5 shadow-sm"><div className="flex items-center gap-2"><span className="rounded-full bg-primary/10 p-2 text-primary"><MessageCircle className="size-5"/></span><div><h2 className="text-lg font-bold">Telegram Connection</h2><p className="text-sm text-muted-foreground">Staff-controlled linking for {PATIENT.name}.</p></div></div><div className="mt-5 rounded-xl border border-border bg-muted/30 p-4"><div className="flex items-center justify-between"><span className="text-sm font-semibold">Current Status</span><StatusBadge status={status}/></div><p className="mt-3 text-sm text-muted-foreground">{status === 'Not Linked' ? 'Generate a temporary invitation to begin.' : status === 'Invite Ready' ? 'Ask the patient to scan the mock QR visual using Telegram.' : 'This patient is connected to the mock Telegram account below.'}</p></div><div className="mt-5 flex flex-wrap gap-2"><Button onClick={generateInvite} disabled={status === 'Linked'}><Smartphone className="size-4"/>Generate QR</Button><Button variant="outline" onClick={linkAccount} disabled={status === 'Linked'}><Link2 className="size-4"/>Link Account</Button></div></section>
    <section className="rounded-2xl border border-border bg-card/95 p-5 shadow-sm"><div className="flex items-center gap-2"><span className="rounded-full bg-primary/10 p-2 text-primary"><ShieldCheck className="size-5"/></span><div><h2 className="text-lg font-bold">Secure Patient Invitation</h2><p className="text-sm text-muted-foreground">Mock invitation for this patient only.</p></div></div>{status === 'Invite Ready' ? <div className="mt-5 flex flex-col items-center gap-4 sm:flex-row sm:items-start"><MockQr/><div className="flex-1"><p className="text-sm font-semibold">Ask the patient to scan this QR code</p><p className="mt-1 text-xs text-muted-foreground">This is a non-functional QR-style mock visual representing a temporary invitation.</p><div className="mt-4 rounded-xl border border-border bg-muted/30 p-3"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Invite Token</p><p className="mt-1 font-mono text-sm font-bold tracking-wider">{MOCK_TOKEN}</p><Button variant="outline" size="sm" className="mt-2" onClick={copyToken}><Copy className="size-3.5"/>{copied ? 'Token Copied' : 'Copy Token'}</Button></div></div></div> : <div className="mt-5 rounded-xl border border-dashed border-border p-8 text-center"><Smartphone className="mx-auto size-10 text-muted-foreground/50"/><p className="mt-3 text-sm font-semibold">No invitation generated</p><p className="mt-1 text-xs text-muted-foreground">Generate a QR to prepare a mock patient-specific invitation.</p></div>}</section></div>
    {status === 'Linked' && <section className="rounded-2xl border border-emerald-200 bg-emerald-50/60 p-5 shadow-sm dark:border-emerald-500/30 dark:bg-emerald-500/10"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-center gap-2"><span className="rounded-full bg-emerald-100 p-2 text-emerald-700 dark:bg-emerald-500/20 dark:text-emerald-300"><CheckCircle2 className="size-5"/></span><div><h2 className="text-lg font-bold">Telegram Account</h2><p className="text-sm text-muted-foreground">Mock linked account information</p></div></div><StatusBadge status="Linked"/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Field label="Name" value="Dara Sok"/><Field label="Username" value="@dara_sok"/><Field label="Telegram User ID" value="684512345"/><Field label="Linked" value="Today, 10:24 AM"/></div><div className="mt-4 flex flex-wrap gap-2"><Button onClick={() => router.push('/telegram-patient-portal')}><ExternalLink className="size-4"/>Open Patient Portal</Button><Button variant="outline" onClick={() => setUnlinkOpen(true)}><Unlink className="size-4"/>Unlink Account</Button></div></section>}
    {unlinkOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={() => setUnlinkOpen(false)}><div className="w-full max-w-md rounded-2xl border border-border bg-card p-6 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold">Unlink Telegram account?</h2><p className="mt-2 text-sm text-muted-foreground">The patient would lose Telegram portal access and require a new invitation to link again.</p></div><button type="button" onClick={() => setUnlinkOpen(false)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted"><X className="size-5"/></button></div><div className="mt-5 flex justify-end gap-2"><Button variant="outline" onClick={() => setUnlinkOpen(false)}>Cancel</Button><Button variant="destructive" onClick={unlinkAccount}>Unlink</Button></div></div></div>}
  </div>;
}